---
name: assign
on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: kentaro-m/auto-assign-action@ed73f90568ce37d22dbbd1a73983738fae329f53 # v1.2.6
        with:
          configuration-path: .github/auto-assign.yml # Only needed if you use something other than .github/auto_assign.yml
