---
name: lint
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: read
  contents: read
  checks: write
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      # Automatically caches for performance as well
      # https://github.com/reviewdog/action-golangci-lint
      # - name: golangci-lint
      #   uses: reviewdog/action-golangci-lint@70498f2d1f75a55ee9a4d719e74e21ed68aebea3 # renovate: tag=v2
      - name: trunk-check
        uses: trunk-io/trunk-action@883e222ef19201ad402ef73e58101ec8186d7d54 # v1
        with:
          arguments: --github-annotate-new-only=false
