---
name: go-tests
on:
  pull_request:
  push:
    tags:
      - v*
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.22.0
          enable_aqua_install: true
          # aqua_opts: ""
        env:
          # AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
          AQUA_LOG_LEVEL: debug
          AQUA_OPTS:
            ""
            # working_directory: "${{ github.workspace }}"

      # - name: aqua-install
      #   run: |
      #     curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
      #     # echo "$HOME/.local/share/aquaproj-aqua/bin" >> $GITHUB_PATH
      #     # [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
      #     ls -lla "${{ github.workspace }}"
      #   env:
      #     AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
      #     AQUA_LOG_LEVEL: debug
      #     AQUA_OPTS: ""
      - name: env-config-go
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Golang caches
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: |
            ${HOME}/.cache/go-build
            ${HOME}/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: mage-init
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua:${PATH}"
          export PATH="$(go env GOPATH)/bin:${PATH}"
          # aqua install # --only-link
          mage init
      - name: mage-testsum
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua:${PATH}"
          export PATH="$(go env GOPATH)/bin:${PATH}"
          mage go:testsum ./...
        env:
          # Race conditions will be hit due to the cli driven tasks and binaries being called.
          GOTEST_DISABLE_RACE: 1
          GOTESTS: "slow"
          GOTEST_FLAGS: "--tags=integration"

      - name: Upload coverage reports to Codecov
        run: |
          # improved codecov with signature verification
          curl https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
          shasum -a 256 -c codecov.SHA256SUM
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
